version: "3.7"
services:
  database:
    container_name: mongodb_simple
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ~/.docker-data/mongodb_simple:/data/db